from typing import Protocol


class IUiComponent(Protocol):
    def __init__(self, parent, bus): ...
    def build(self) -> None: ...


class ILoanAppView(IUiComponent, Protocol):
    def execute(self) -> None: ...
    def show_message(self, message: str) -> None: ...
